### ISSUE TITLE
Enhancement: add structured fact containing list of modules

### ISSUE THREAD

**Issue by faxm0dem** [voxpupuli/puppet-kmod#33]
I already wrote [something similar](https://github.com/ccin2p3/puppet-afs/blob/f/kmod_fact/lib/facter/openafs_module.rb) if you could have a look and tell me if you'd accept a PR in this regard.
Proposed format (structured fact):

```
☠ facter -p kmod
["libata","sg","e1000", ... ]
```

Or

```
☠ facter -p kmod
{"nfs"=>{"size"=>188136,"used_by"=>[]},"nfs_acl"=>{"size"=>12511,"used_by"=>["nfsd"]},...}
```

**Comment by jhoblitt** [comment]
I am also desiring a fact for all loaded modules.  @faxm0dem's second example seems about right as it would generally be more convenient to test if a module is loaded via a hash lookup rather than terating across a list.

**Comment by faxm0dem** [comment]
Then again we could provide functions that would abstract this fact *e.g.* `kmod_is_loaded('openafs')`

**Comment by faxm0dem** [comment]
wow time moves too fast

**Comment by kenyon** [comment]
Looks like #44 should have closed this, so closing it now.
